// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxLXP5o60waO9dgenHbUeVN92Q-d-Oxec',
    appId: '1:1093163651213:web:dbe576acd98070c22592c4',
    messagingSenderId: '1093163651213',
    projectId: 'chatify-cbf29',
    authDomain: 'chatify-cbf29.firebaseapp.com',
    storageBucket: 'chatify-cbf29.appspot.com',
    measurementId: 'G-6R4LK72NXY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2qMie_alcHpe5776jHC6UWl5BsnvHEYw',
    appId: '1:1093163651213:android:c8771e6bbd49a2832592c4',
    messagingSenderId: '1093163651213',
    projectId: 'chatify-cbf29',
    storageBucket: 'chatify-cbf29.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVQGo3E-cO26t5Hd55fg1P8O4zVW7TLag',
    appId: '1:1093163651213:ios:2a307dbd5ecdc2952592c4',
    messagingSenderId: '1093163651213',
    projectId: 'chatify-cbf29',
    storageBucket: 'chatify-cbf29.appspot.com',
    iosBundleId: 'com.example.chatify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVQGo3E-cO26t5Hd55fg1P8O4zVW7TLag',
    appId: '1:1093163651213:ios:2a307dbd5ecdc2952592c4',
    messagingSenderId: '1093163651213',
    projectId: 'chatify-cbf29',
    storageBucket: 'chatify-cbf29.appspot.com',
    iosBundleId: 'com.example.chatify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxLXP5o60waO9dgenHbUeVN92Q-d-Oxec',
    appId: '1:1093163651213:web:c96e9033fe9ec8652592c4',
    messagingSenderId: '1093163651213',
    projectId: 'chatify-cbf29',
    authDomain: 'chatify-cbf29.firebaseapp.com',
    storageBucket: 'chatify-cbf29.appspot.com',
    measurementId: 'G-SMY5XCXGG0',
  );
}
